### ISSUE TITLE
python 3.9 浏览器卡死 白屏

### ISSUE THREAD

**Issue by tangyanglai** [chengxinli-zn/taobao-tianmao-Timed-spike#3]
先感谢作者的分享

python 3.9
pyppeteer版本0.2.5
浏览器版本是588429

怀疑是安装的坏境问题。查不到资料

**Comment by chengxinli-zn** [comment]
Chromium没有跳出两个浏览器吗？或者安装固定版本 我的是 pyppeteer  0.2.2

**Comment by chengxinli-zn** [comment]
Chromium没有跳出两个浏览器吗？一个是空白的，另一个无痕的浏览器。 或者安装固定版本 我的是 pyppeteer 0.2.2

> 
![截屏2021-01-11 上午11 24 43](https://user-images.githubusercontent.com/74350085/104144769-9d8d9680-53ff-11eb-9d1f-e2b4dfa6c180.png)

**Comment by tangyanglai** [comment]
没有 只跳出一个。我试下 pyppeteer 0.2.2

**Comment by tangyanglai** [comment]
还是一样的现象。问下， 作者用的python版本是多少？webscocket要不要改成6.0？

**Comment by tangyanglai** [comment]
另外一台正常的，不过被淘宝检测到了。。。。
